# Generated by Django 4.2.2 on 2023-08-01 17:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('allow_status', models.IntegerField(choices=[(0, 'tematic'), (1, 'embedding'), (2, 'all')], default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_records', models.IntegerField(default=9999, null=True)),
                ('used_records', models.IntegerField(default=0, null=True)),
                ('topic', models.IntegerField(choices=[(0, 'search_tematic'), (1, 'analise_tematic'), (2, 'search_ddi')], default=0)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2023, 8, 1, 20, 38, 47, 381187))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
