# Generated by Django 4.2.2 on 2023-07-05 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, verbose_name='PMID')),
                ('aid', models.CharField(max_length=64, verbose_name='AID')),
                ('titl', models.CharField(max_length=250, verbose_name='TITL')),
                ('mesh', models.TextField(verbose_name='MESH')),
                ('majr', models.TextField(verbose_name='MAJR')),
                ('subh', models.TextField(verbose_name='SUBH')),
                ('auth', models.TextField(verbose_name='AUTH')),
                ('jour', models.TextField(verbose_name='JOUR')),
                ('affl', models.TextField(verbose_name='AFFL')),
                ('pdat', models.CharField(max_length=32, verbose_name='PDAT')),
                ('tiab', models.TextField(verbose_name='TIAB')),
                ('ptyp', models.TextField(verbose_name='PTYP')),
                ('url', models.CharField(max_length=250, verbose_name='URL_LINK')),
                ('urlaid', models.CharField(max_length=250, verbose_name='URL_AID')),
                ('pt', models.TextField(verbose_name='PT')),
                ('pl', models.TextField(verbose_name='PL')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=150, null=True)),
                ('query', models.TextField()),
                ('full_query', models.TextField()),
                ('translation_stack', models.TextField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'processing'), (1, 'done'), (2, 'error')], default=0)),
                ('count', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
