# Generated by Django 4.2.2 on 2023-07-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_article_pdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdat',
            field=models.CharField(max_length=32, verbose_name='PDAT'),
        ),
    ]
