# Generated by Django 4.2.2 on 2023-07-06 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_article_pdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_search', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=150, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'processing'), (1, 'done'), (2, 'error')], default=0)),
                ('type_analise', models.IntegerField(choices=[(0, 'processing'), (1, 'done'), (2, 'error')], default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_analise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
