# Generated by Django 4.2.2 on 2023-07-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_task_user_taskanalise'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='taskanalise',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
